$(document).ready(function(){
	$("#mymodalform").submit(function(e){
		$.ajax({
			url:'newfetch.php',
			type:'POST',
			data:$("#mymodalform").serialize(),
			success:function(res){
				console.log(res);
			},
			error:function(err){
				console.log(err);
			},
		});
		e.preventDefault();
	});
});